// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LibraryInstallerExtension.Vsix
{
    static class Vsix
    {
        public const string Id = "25e0d980-2418-4763-8740-0f51d298e290";
        public const string Name = "Library Installer Extension Example";
        public const string Description = @"A Library Installer extension.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
